AddUpdateDeleteApp/AddUpdateDeleteApp/Models/ErrorViewModel.cs
using System;

namespace AddUpdateDeleteApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AddUpdateDeleteApp/AddUpdateDeleteApp/Models/PersonageViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AddUpdateDeleteApp.Models
{
    public class PersonageViewModel
    {
        public int PersonageViewModelId { get; set; }
        [Required(ErrorMessage ="Enter Person's Name")]
        public string Name { get; set; }
        [StringLength(maximumLength : 11)]
        [Display(Name ="Phone Number")]
        [Required(ErrorMessage = "Enter Person's Phone Number")]
        public string PhoneNo { get; set; }
        [Required(ErrorMessage ="Enter Email Address")]
        [RegularExpression(@"^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter correct email address")]
        public string Email { get; set; }
        [Required(ErrorMessage ="Enter Person Address")]
        public string Address { get; set; }
        [Required(ErrorMessage ="Select IsActive")]
        public bool  IsActive { get; set; }


    }
}

AddUpdateDeleteApp/AddUpdateDeleteApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AddUpdateDeleteApp.Models;

namespace AddUpdateDeleteApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AddUpdateDeleteApp/AddUpdateDeleteApp/Controllers/PersonageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AddUpdateDeleteApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Person.BLL.Contract;
using Person.DatabaseContext.DatabaseContext;
using Person.Models.EntityModels;

namespace AddUpdateDeleteApp.Controllers
{
    public class PersonageController : Controller
    {
        private IPersonageManager _personageManager;

        public PersonageController(IPersonageManager personageManager)
        {
            _personageManager = personageManager;
        }
        public IActionResult PersonageCreate()
        {
            ViewBag.Persons = new SelectList(_personageManager.GetAll());

            return View();
        }
        [HttpPost]
        public IActionResult PersonageCreate(Personage personage)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    bool isSaved = _personageManager.Add(personage);
                    if (isSaved)
                    {
                        ViewBag.Message = "Personage Saved Successfully";
                    }
                    else
                    {
                        ViewBag.Message = "Personage Saved Failled";
                    }
                }
                catch (Exception e)
                {

                    ViewBag.PersonageExistMessage = e.Message;
                }
               
            }
            return View();
        }

        public IActionResult PersonageList()
        {
            var personage = _personageManager.GetAll();
            return View(personage);
        }
        public IActionResult PersonageDataTable()
        {
            var personage = _personageManager.GetAll();
            return Json(personage);
        }

        //public IActionResult PersonagePartial()
        //{
        //    var persons = _personageManager.GetAll();
        //    if (persons != null)
        //    {
        //        return PartialView("_PersonageDetailListPartial", persons);
        //    }
        //    else
        //    {
        //        return null;
        //    }
        //}

        public IActionResult PersonageEdit(int id)
        {
            Personage person = _personageManager.GetInfoBy(id);
            return View(person);
        }
        [HttpPost]
        public IActionResult PersonageEdit(Personage personage)
        {

            if (ModelState.IsValid)
            {
                /*bool IsUpdated =*/ _personageManager.Update(personage);
                //if (IsUpdated)
                //{
                //    ViewBag.Message = "Personage Updated Successfuly";
                //}
                ////else
                //{
                //    ViewBag.Message = "Personage Update Failled";
                //}
            }


            return RedirectToRoute("ListRoute");
        }

       
        public IActionResult PersonageRemove(int id)
        {
            Personage person = _personageManager.GetInfoBy(id);
            return View(person);
        }
        [HttpPost]
        public IActionResult PersonageRemove(Personage personage)
        {

            //if (ModelState.IsValid)
            //{
            /*bool isRemoved =*/ _personageManager.Remove(personage);
            //    if (isRemoved)
            //    {
            //        ViewBag.Message = "Personage Removed Successfylly";
            //    }
            //    else
            //    {
            //        ViewBag.Message = "Personage Remove Failled";
            //    }
            //}
            //return View();
            return RedirectToRoute("ListRoute");
        }


        public IActionResult PersonageInfo(int id)
        {
            Personage person = _personageManager.GetInfoBy(id);
            return View(person);
        }


    }
}

AddUpdateDeleteApp/AddUpdateDeleteApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AddUpdateDeleteApp/AddUpdateDeleteApp/Views/Personage/PersonageCreate.cshtml
@model PersonageViewModel
@{
    ViewData["Title"] = "PersonageCreate";
    
}

<h1>Personage Create</h1>

<div>
    <a class="btn btn-dark" asp-action="PersonageList">Back to Personage List</a>
</div>

<hr />
<div class="row">
    <div class="col-lg-4">
        @if (ViewBag.Message != null)
        {
            <div class="alert-danger">@ViewBag.Message</div>
        }
        @if (ViewBag.PersonageExistMessage != null)
        {
            <div class="alert-danger">@ViewBag.PersonageExistMessage</div>
        }

        <form asp-action="PersonageCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNo" class="control-label"></label>
                <input asp-for="PhoneNo" class="form-control" />
                <span asp-validation-for="PhoneNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group checkbox">
                <input asp-for="IsActive" checked="checked" />
                <label asp-for="IsActive">
                </label>
            </div>
            <div class="form-group">
                <input type="submit" id="ButtonList" value="Create" class="btn btn-primary" />
            </div>
        </form>

    </div>

    @*<div class="col-lg-4" id="PartialList">


    </div>*@

   <div class="col-lg-6">
            <table class="table table-active table-bordered" id="TablePerson">
                <thead class="bg-secondary">
                    <tr>
                        <th>
                            Name
                        </th>
                        <th>
                            PhoneNo
                        </th>
                        <th>
                            Email
                        </th>
                        <th>
                            Address
                        </th>
                        <th>
                            IsActive
                        </th>
                       
                    </tr>
                </thead>
                <tbody>
                    @*@foreach (var item in ViewBag.a)
                    {
                        <tr>
                            <td>
                                item.Name
                            </td>
                            <td>
                               item.PhoneNo
                            </td>
                            <td>
                                 item.Email
                            </td>
                            <td>
                                 item.Address
                            </td>
                            <td>
                                item.IsActive
                            </td>

                        </tr>
                    }*@


                </tbody>
            </table>

        </div>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    @*<script>
        $(document).ready(function () {
            $("#ButtonList").click(function () {

                //var json = { departmentId: departmentId }
                $.ajax({
                    type: "POST",
                    url: "/Personage/PersonagePartial",
                    //data: json,
                    success: function (response) {
                        $('#PartialList').html(response);

                    }


                });

            });
        });
       
    </script>*@


   <script src="~/lib/datatables/js/dataTables.bootstrap.js"></script>
            <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
            <script>
                $(document).ready(function () {

               $("#TablePerson").DataTable({
                   "ajax" :{

                            "url": "/Personage/PersonageDataTable",
                            "type": "GET",
                            
                            "data": "json"
               
                       },
                       "columns": [

                           { "data": "Name", "autowidth": "true" },
                           { "data": " PhoneNo", "autowidth": "true" },
                           { "data": "Email", "autowidth": "true" },
                           { "data": " Address", "autowidth": "true" },
                           { "data": "IsActive", "autowidth": "true" }
                           
                       ]
                       
                   })
                })
                
            </script>

        }

        @section styles{
            <link href="~/lib/datatables/css/jquery.dataTables.css" rel="stylesheet" />
            <link href="~/lib/datatables/css/jquery.dataTables_themeroller.css" rel="stylesheet" />
}

AddUpdateDeleteApp/AddUpdateDeleteApp/Views/Personage/PersonageEdit.cshtml
@model Person.Models.EntityModels.Personage

@{
    ViewData["Title"] = "PersonageEdit";
}

<h1>Personage Edit</h1>
<div>
    <a class="btn btn-dark" asp-action="PersonageList">Back to Personage List</a>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        @if (ViewBag.Message != null)
        {
            <div class="alert-danger">@ViewBag.Message</div>
        }
            <form asp-action="PersonageEdit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ID" />
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNo" class="control-label"></label>
                    <input asp-for="PhoneNo" class="form-control" />
                    <span asp-validation-for="PhoneNo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group checkbox">
                    <input asp-for="IsActive"  />
                    <label asp-for="IsActive">
                    </label>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}


}

AddUpdateDeleteApp/AddUpdateDeleteApp/Views/Personage/PersonageInfo.cshtml
@model Person.Models.EntityModels.Personage

@{
    ViewData["Title"] = "PersonageRemove";
}

<div>
    <h4>Personage Details</h4>
    <hr />
    <dl class="row">
        
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
    <a class="btn btn-dark" asp-action="PersonageList">Personage List</a> |
    <a class="btn btn-dark" asp-action="PersonageEdit" asp-route-id="@Model.ID">Edit</a> |   
    <a class="btn btn-dark" asp-action="PersonageRemove" asp-route-id="@Model.ID">Delete</a>

</div>

AddUpdateDeleteApp/AddUpdateDeleteApp/Views/Personage/PersonageList.cshtml
@model IEnumerable<Person.Models.EntityModels.Personage>

@{
    ViewData["Title"] = "PersonageList";
}

<h1>PersonageList</h1>

<p>
    <a class="btn btn-dark" asp-action="PersonageCreate">Create New</a>
</p>
<table class="table table-active table-bordered">
    <thead class="bg-secondary">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                <a class="btn btn-dark" asp-action="PersonageEdit" asp-route-id="@item.ID">Edit</a> |
                <a class="btn btn-dark" asp-action="PersonageInfo" asp-route-id="@item.ID">Details</a> |
                <a class="btn btn-dark" asp-action="PersonageRemove" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

AddUpdateDeleteApp/AddUpdateDeleteApp/Views/Personage/PersonageRemove.cshtml
@model Person.Models.EntityModels.Personage

@{
    ViewData["Title"] = "PersonageRemove";
}

<h1>Personage Remove</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Personage</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
    
    <form asp-action="PersonageRemove">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-dark" asp-action="PersonageList">Personage List</a>
    </form>
</div>

AddUpdateDeleteApp/AddUpdateDeleteApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AddUpdateDeleteApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />

    @RenderSection("styles",required:false)
</head>
<body>
    <header>
       
       
            <nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top" style=" border: 1px solid darkmagenta">
                <a href="/Home/Index" class="navbar-brand">logo</a>
                <div class="container">
                    <button type="button" class="navbar-toggler" data-target="#menu" data-toggle="collapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="menu">
                        <ul class="navbar-nav mr-auto" style="border: 1px solid darkmagenta">
                            <li><a href="/Home/Index"class="nav-link" style="color: white">Home</a></li>
                            
                            <li class="dropdown">
                                <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">SetUp</a>

                                <ul class="dropdown-menu bg-dark" style="border: 1px solid darkmagenta">
                                    <li><a href="/Personage/PersonageCreate" class="nav-link">Person Create</a></li>
                                    <li><a href="/Personage/PersonageList" class="nav-link">Person List</a></li>                                   
                                </ul>
                            </li>
                           
                        </ul>

                        <ul class="navbar-nav" style="border: 1px solid darkmagenta">
                            <li><a href="" class="nav-link" data-toggle="modal" data-target="#modal">Login</a></li>
                            <li><a href="" class="nav-link" data-toggle="modal" data-target="#modal2">Sign Up</a></li>
                        </ul>
                    </div>
                </div>

            </nav>
</header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - AddUpdateDeleteApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

AddUpdateDeleteApp/AddUpdateDeleteApp/Views/Shared/_PersonageEditPartial/Edit.cshtml
@model PersonageViewModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="row">
    <div class="col-md-4">
        @if (ViewBag.Message != null)
        {
            <div class="alert-info">@ViewBag.Message</div>
        }
        <form asp-action="PersonEdit" asp-controller="Personage" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PersonageViewModelId" />
            @*<div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <select asp-for="Email" asp-items=" Model.Emails" id="PersonageEmail" class="form-control">
                    <option value="">--select--</option>
                </select>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>*@

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" id="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNo" class="control-label"></label>
                <input asp-for="PhoneNo" id="Phone" class="form-control" />
                <span asp-validation-for="PhoneNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" id="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" id="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

AddUpdateDeleteApp/AddUpdateDeleteApp/Views/Shared/_PersonageEditPartial/_PersonageDetailListPartial.cshtml
@model IEnumerable<Person.Models.EntityModels.Personage>

<table class="table table-active table-bordered">
    <thead class="bg-secondary">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsActive)
                </td>
                <td>
                    <a asp-action="PersonageEdit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="PersonageRemove" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>